// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZmOo4IDRSigKnBwIhFWCXhOQTbZi_bMM',
    appId: '1:674907527694:web:0316c0ec4e6021fe7fba5f',
    messagingSenderId: '674907527694',
    projectId: 'solar-max-d76df',
    authDomain: 'solar-max-d76df.firebaseapp.com',
    databaseURL: 'https://solar-max-d76df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-max-d76df.firebasestorage.app',
    measurementId: 'G-0SJ87FEFRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABPsqCxpWxvKcAY3hDEtZfn51LhRlDTRU',
    appId: '1:674907527694:android:7e861fbe9343be207fba5f',
    messagingSenderId: '674907527694',
    projectId: 'solar-max-d76df',
    databaseURL: 'https://solar-max-d76df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-max-d76df.firebasestorage.app',
  );
}
